/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Pantallas;

import com.sun.source.tree.ParenthesizedTree;

/**
 *
 * @author Arturo ITSON
 */
public class DlgFiltrosBuscador extends javax.swing.JDialog {

    
    FrmBuscador buscador;
    
    /**
     * Creates new form DlgFiltrosBuscador
     */
    public DlgFiltrosBuscador(java.awt.Frame parent, boolean modal, FrmBuscador buscador) {
        super(parent, modal);
        this.buscador = buscador;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jblFlitrosAlbumes = new javax.swing.JLabel();
        cbNombreAlbum = new javax.swing.JCheckBox();
        cbGeneroAlbum = new javax.swing.JCheckBox();
        cbFecha = new javax.swing.JCheckBox();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Filtros Buscador");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jblFlitrosAlbumes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblFlitrosAlbumes.setForeground(new java.awt.Color(0, 0, 0));
        jblFlitrosAlbumes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblFlitrosAlbumes.setText("Filtros Albumes");

        cbNombreAlbum.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbNombreAlbum.setForeground(new java.awt.Color(0, 0, 0));
        cbNombreAlbum.setText("Nombre Album");
        cbNombreAlbum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbNombreAlbumMouseClicked(evt);
            }
        });
        cbNombreAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNombreAlbumActionPerformed(evt);
            }
        });

        cbGeneroAlbum.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbGeneroAlbum.setForeground(new java.awt.Color(0, 0, 0));
        cbGeneroAlbum.setText("Genero Album");
        cbGeneroAlbum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbGeneroAlbumMouseClicked(evt);
            }
        });
        cbGeneroAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGeneroAlbumActionPerformed(evt);
            }
        });

        cbFecha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbFecha.setForeground(new java.awt.Color(0, 0, 0));
        cbFecha.setText("Fecha Lanzamiento");
        cbFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbFechaMouseClicked(evt);
            }
        });
        cbFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFechaActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbGeneroAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNombreAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolver)
                    .addComponent(jblFlitrosAlbumes, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jblFlitrosAlbumes)
                .addGap(27, 27, 27)
                .addComponent(cbNombreAlbum)
                .addGap(18, 18, 18)
                .addComponent(cbGeneroAlbum)
                .addGap(18, 18, 18)
                .addComponent(cbFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFechaActionPerformed
        // TODO add your handling code here:
        cbGeneroAlbum.setSelected(false);
        cbNombreAlbum.setSelected(false);
        if(cbFecha.isSelected()){
        buscador.jblFormatoFecha.setText("Formato fecha: 'dd/MM/yyyy'");
        }
        else{
            buscador.jblFormatoFecha.setText("");
        }
    }//GEN-LAST:event_cbFechaActionPerformed

    private void cbNombreAlbumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbNombreAlbumMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbNombreAlbumMouseClicked

    private void cbGeneroAlbumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbGeneroAlbumMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cbGeneroAlbumMouseClicked

    private void cbFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbFechaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFechaMouseClicked

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void cbGeneroAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGeneroAlbumActionPerformed
        // TODO add your handling code here:
        cbFecha.setSelected(false);
        cbNombreAlbum.setSelected(false);
        buscador.jblFormatoFecha.setText("");
    }//GEN-LAST:event_cbGeneroAlbumActionPerformed

    private void cbNombreAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNombreAlbumActionPerformed
        // TODO add your handling code here:
        cbFecha.setSelected(false);
        cbGeneroAlbum.setSelected(false);
        buscador.jblFormatoFecha.setText("");
        
    }//GEN-LAST:event_cbNombreAlbumActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    public javax.swing.JCheckBox cbFecha;
    public javax.swing.JCheckBox cbGeneroAlbum;
    public javax.swing.JCheckBox cbNombreAlbum;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jblFlitrosAlbumes;
    // End of variables declaration//GEN-END:variables
}
