/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Pantallas;

import com.sun.source.tree.ParenthesizedTree;

/**
 *
 * @author Arturo ITSON
 */
public class DlgFiltrosUsuarioFavoritos extends javax.swing.JDialog {

    
    FrmUsuarioFavoritos uFav;
    
    /**
     * Creates new form DlgFiltrosBuscador
     */
    public DlgFiltrosUsuarioFavoritos(java.awt.Frame parent, boolean modal, FrmUsuarioFavoritos uFav) {
        super(parent, modal);
        this.uFav = uFav;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jblFlitrosAlbumes = new javax.swing.JLabel();
        cbGenero = new javax.swing.JCheckBox();
        cbFecha = new javax.swing.JCheckBox();
        btnVolver = new javax.swing.JButton();
        jblFlitroTipo = new javax.swing.JLabel();
        cbcTipo = new javax.swing.JComboBox<>();
        jblFlitroTipo1 = new javax.swing.JLabel();
        jblFlitroTipo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Filtros Buscador");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jblFlitrosAlbumes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblFlitrosAlbumes.setForeground(new java.awt.Color(0, 0, 0));
        jblFlitrosAlbumes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblFlitrosAlbumes.setText("Filtros Favoritos");

        cbGenero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbGenero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbGeneroMouseClicked(evt);
            }
        });
        cbGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGeneroActionPerformed(evt);
            }
        });

        cbFecha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbFechaMouseClicked(evt);
            }
        });
        cbFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFechaActionPerformed(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(8, 148, 249));
        btnVolver.setForeground(new java.awt.Color(0, 0, 0));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jblFlitroTipo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jblFlitroTipo.setForeground(new java.awt.Color(0, 0, 0));
        jblFlitroTipo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jblFlitroTipo.setText("Tipo");

        cbcTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Artista", "Album", "Cancion" }));
        cbcTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcTipoActionPerformed(evt);
            }
        });

        jblFlitroTipo1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jblFlitroTipo1.setForeground(new java.awt.Color(0, 0, 0));
        jblFlitroTipo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jblFlitroTipo1.setText("Genero");

        jblFlitroTipo2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jblFlitroTipo2.setForeground(new java.awt.Color(0, 0, 0));
        jblFlitroTipo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jblFlitroTipo2.setText("Fecha Agregacion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVolver)
                    .addComponent(jblFlitrosAlbumes, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jblFlitroTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jblFlitroTipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jblFlitroTipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbcTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jblFlitrosAlbumes)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblFlitroTipo)
                    .addComponent(cbcTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbGenero)
                    .addComponent(jblFlitroTipo1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbFecha)
                    .addComponent(jblFlitroTipo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFechaActionPerformed
        // TODO add your handling code here:
        cbGenero.setSelected(false);
        cbcTipo.setSelectedIndex(0);
        if(cbFecha.isSelected()){
        uFav.jblFormatoFecha.setText("Formato fecha: 'dd/MM/yyyy'");
        }
        else{
            uFav.jblFormatoFecha.setText("");
        }
    }//GEN-LAST:event_cbFechaActionPerformed

    private void cbGeneroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbGeneroMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cbGeneroMouseClicked

    private void cbFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbFechaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFechaMouseClicked

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void cbGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGeneroActionPerformed
        // TODO add your handling code here:
        cbFecha.setSelected(false);
        uFav.jblFormatoFecha.setText("");
        cbcTipo.setSelectedIndex(0);
    }//GEN-LAST:event_cbGeneroActionPerformed

    private void cbcTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcTipoActionPerformed
        // TODO add your handling code here:
        if(!cbcTipo.getSelectedItem().toString().equalsIgnoreCase("Ninguno")){
            cbFecha.setEnabled(false);
            cbGenero.setEnabled(false);
        }
        else{
            cbFecha.setEnabled(true);
            cbGenero.setEnabled(true);
        }
            
        
        
    }//GEN-LAST:event_cbcTipoActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    public javax.swing.JCheckBox cbFecha;
    public javax.swing.JCheckBox cbGenero;
    protected javax.swing.JComboBox<String> cbcTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jblFlitroTipo;
    private javax.swing.JLabel jblFlitroTipo1;
    private javax.swing.JLabel jblFlitroTipo2;
    private javax.swing.JLabel jblFlitrosAlbumes;
    // End of variables declaration//GEN-END:variables
}
