/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Pantallas;

import java.util.List;

/**
 *
 * @author Arturo ITSON
 */
public class DlgIntegrantes extends javax.swing.JDialog {

    
    List<String> integrantes;
    
    /**
     * Creates new form DlgIntegrantes
     */
    public DlgIntegrantes(List<String> integrantes) {
        this.integrantes = integrantes;
        
        initComponents();
        
        cargarDatos(integrantes);
    }

    
    public void cargarDatos(List<String> integrantes){
    
    // Lista de datos dinámicos
        List<String> datos = integrantes;

        // Construir texto HTML
        StringBuilder textoHTML = new StringBuilder("<html>");
        for (String dato : datos) {
            textoHTML.append(dato).append("<br>");
        }
        textoHTML.append("</html>");
        
        jblIntegrantes.setText(textoHTML.toString());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jIntegrantesTitulo = new javax.swing.JLabel();
        jblIntegrantes = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Integrantes");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jIntegrantesTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jIntegrantesTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jIntegrantesTitulo.setText("Integrantes");

        jblIntegrantes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jblIntegrantes.setForeground(new java.awt.Color(0, 0, 0));
        jblIntegrantes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblIntegrantes.setText("Integrantes");
        jblIntegrantes.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnRegresar.setBackground(new java.awt.Color(8, 148, 249));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jIntegrantesTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jblIntegrantes, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnRegresar)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jIntegrantesTitulo)
                .addGap(28, 28, 28)
                .addComponent(jblIntegrantes, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegresar)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jIntegrantesTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jblIntegrantes;
    // End of variables declaration//GEN-END:variables
}
