/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import dtos.AlbumDTO;
import dtos.ArtistaDTO;
import dtos.CancionDTO;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import negocio.ArtistaNegocio;
import negocio.IArtistaNegocio;
import org.bson.types.ObjectId;

/**
 *
 * @author Arturo ITSON
 */
public class FrmBuscador extends javax.swing.JFrame {

    
    FrmUsuarioPerfil perfil;
    
    static List<ArtistaDTO> artistas;
    static List<AlbumDTO> albumes;
    static List<CancionDTO> canciones;
    
    static int indiceArtistaA = 0;
    static int indiceArtistaB = 1;
    static int indiceArtistaC = 2;
    
    static int indiceAlbumA = 0;
    static int indiceAlbumB = 1;
    static int indiceAlbumC = 2;
    
    static int indiceCancionA = 0;
    static int indiceCancionB = 1;
    static int indiceCancionC = 2;
    
    IArtistaNegocio negocio = new ArtistaNegocio();
    
    /**
     * Creates new form FrmBuscador
     */
    public FrmBuscador(FrmUsuarioPerfil perfil) {
        this.perfil = perfil;
        
        
        
        initComponents();
        
        btnRetrocederAlbum.setEnabled(false);
        btnRetrocederArtista.setEnabled(false);
        btnRetrocederCancion.setEnabled(false);
        
        obtenerDatos();
        cargarDatos();
    }

    
    public void obtenerDatos(){
        
        
        artistas = negocio.obtenerTodos();
        
        albumes = negocio.obtenerTodosAlbumesEnArtista();
                
        canciones = negocio.obtenerTodasCancionesEnArtista();
        
        
        System.out.println("alb" + albumes.size());

        System.out.println("ca" + canciones.size());
        
    }
    
    public void cargarDatos(){
    
        jblNombreArtista1.setText(artistas.get(0).getNombreArtista());
        setImagenLabel(jblArtista1, artistas.get(0).getImagen());
        System.out.println(artistas.get(0).toString());
        
        jblNombreArtista2.setText(artistas.get(1).getNombreArtista());
        setImagenLabel(jblArtista2, artistas.get(1).getImagen());
        
        jblNombreArtista3.setText(artistas.get(2).getNombreArtista());
        setImagenLabel(jblArtista3, artistas.get(2).getImagen());
        
        

        jblNombreAlbum1.setText(albumes.get(0).getNombre());
        setImagenLabel(jblAlbum1, artistas.get(0).getImagen());
        System.out.println(albumes.get(0).toString());
        
        jblNombreAlbum2.setText(albumes.get(1).getNombre());
        setImagenLabel(jblAlbum2, albumes.get(1).getImagen());
        
        jblNombreAlbum3.setText(albumes.get(2).getNombre());
        setImagenLabel(jblAlbum3, albumes.get(2).getImagen());
        
        
        
        jblNombreCancion1.setText(canciones.get(0).getNombreCancion());
        System.out.println(canciones.get(0).toString());
        setImagenLabel(jblCancion1, negocio.obtenerImagenPorIdCancion(canciones.get(0).getIdCancion()));
        
        jblNombreCancion2.setText(canciones.get(1).getNombreCancion());
        setImagenLabel(jblCancion2, negocio.obtenerImagenPorIdCancion(canciones.get(1).getIdCancion()));
        
        jblNombreCancion3.setText(canciones.get(2).getNombreCancion());
        setImagenLabel(jblCancion3, negocio.obtenerImagenPorIdCancion(canciones.get(2).getIdCancion()));

    }
    
    
        /**
     * Metodo que coloca una imagen de el logo de cinepolis en la interfaz
     * @param nombreJlb el jlabel que sera reemplazado por una imagen
     * @param ruta la direccion donde se encuentra la imagen
     */
    private void setImagenLabel(JLabel nombreJlb, String ruta){
    
        ImageIcon image = new ImageIcon(ruta);
        
        Icon icon = new ImageIcon(
        image.getImage().getScaledInstance(nombreJlb.getWidth(), nombreJlb.getHeight(), Image.SCALE_DEFAULT));
        
        nombreJlb.setIcon(icon);
        
        this.repaint();
   
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jblNombreArtista5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnBuscador = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        jblBuscar = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnFiltros = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jblArtistas = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        btnRetrocederArtista = new javax.swing.JButton();
        btnAvanzarArtista = new javax.swing.JButton();
        jblArtista1 = new javax.swing.JLabel();
        jblArtista2 = new javax.swing.JLabel();
        jblArtista3 = new javax.swing.JLabel();
        jblNombreArtista1 = new javax.swing.JLabel();
        jblNombreArtista2 = new javax.swing.JLabel();
        jblNombreArtista3 = new javax.swing.JLabel();
        jblArtistaFavorito1 = new javax.swing.JLabel();
        jblArtistaFavorito2 = new javax.swing.JLabel();
        jblArtistaFavorito3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnRetrocederAlbum = new javax.swing.JButton();
        btnAvanzarAlbum = new javax.swing.JButton();
        jblAlbum1 = new javax.swing.JLabel();
        jblAlbum2 = new javax.swing.JLabel();
        jblAlbum3 = new javax.swing.JLabel();
        jblNombreAlbum1 = new javax.swing.JLabel();
        jblNombreAlbum2 = new javax.swing.JLabel();
        jblNombreAlbum3 = new javax.swing.JLabel();
        jblAlbumFavorito1 = new javax.swing.JLabel();
        jblAlbumFavorito2 = new javax.swing.JLabel();
        jblAlbumFavorito3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnRetrocederCancion = new javax.swing.JButton();
        btnAvanzarCancion = new javax.swing.JButton();
        jblCancion1 = new javax.swing.JLabel();
        jblCancion2 = new javax.swing.JLabel();
        jblCancion3 = new javax.swing.JLabel();
        jblNombreCancion1 = new javax.swing.JLabel();
        jblNombreCancion2 = new javax.swing.JLabel();
        jblNombreCancion3 = new javax.swing.JLabel();
        jblCancionFavorito1 = new javax.swing.JLabel();
        jblCancionFavorito2 = new javax.swing.JLabel();
        jblCancionFavorito3 = new javax.swing.JLabel();
        jblAlbumes = new javax.swing.JLabel();
        jblCanciones = new javax.swing.JLabel();

        jblNombreArtista5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buscador");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setPreferredSize(new java.awt.Dimension(475, 76));

        btnBuscador.setBackground(new java.awt.Color(8, 148, 249));
        btnBuscador.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnBuscador.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscador.setText("Buscador");
        btnBuscador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscadorActionPerformed(evt);
            }
        });

        btnPerfil.setBackground(new java.awt.Color(217, 217, 217));
        btnPerfil.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnPerfil.setForeground(new java.awt.Color(0, 0, 0));
        btnPerfil.setText("Perfil");
        btnPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 235, Short.MAX_VALUE)
                .addComponent(btnBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 243, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuscador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        txtBuscar.setBackground(new java.awt.Color(204, 204, 204));
        txtBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jblBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblBuscar.setForeground(new java.awt.Color(0, 0, 0));
        jblBuscar.setText("Buscar");

        btnBuscar.setText("Buscar");

        btnFiltros.setText("Filtros");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jblBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFiltros))
                    .addComponent(txtBuscar))
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addGap(33, 33, 33))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblBuscar)
                    .addComponent(btnFiltros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(14, 14, 14))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jblArtistas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblArtistas.setForeground(new java.awt.Color(0, 0, 0));
        jblArtistas.setText("Artistas");

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        btnRetrocederArtista.setBackground(new java.awt.Color(8, 148, 249));
        btnRetrocederArtista.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnRetrocederArtista.setForeground(new java.awt.Color(0, 0, 0));
        btnRetrocederArtista.setText("<");
        btnRetrocederArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocederArtistaActionPerformed(evt);
            }
        });

        btnAvanzarArtista.setBackground(new java.awt.Color(8, 148, 249));
        btnAvanzarArtista.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnAvanzarArtista.setForeground(new java.awt.Color(0, 0, 0));
        btnAvanzarArtista.setText(">");
        btnAvanzarArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvanzarArtistaActionPerformed(evt);
            }
        });

        jblArtista1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jblArtista1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblArtista1MouseClicked(evt);
            }
        });

        jblArtista2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jblArtista2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblArtista2MouseClicked(evt);
            }
        });

        jblArtista3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jblArtista3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblArtista3MouseClicked(evt);
            }
        });

        jblNombreArtista1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblNombreArtista1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jblNombreArtista2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblNombreArtista2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jblNombreArtista3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblNombreArtista3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jblArtistaFavorito1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jblArtistaFavorito2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jblArtistaFavorito3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(btnRetrocederArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jblNombreArtista1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jblArtista1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jblArtistaFavorito1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jblArtista2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblNombreArtista2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jblArtistaFavorito2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jblNombreArtista3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnAvanzarArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jblArtista3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jblArtistaFavorito3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jblArtistaFavorito2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jblArtista3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jblArtistaFavorito3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jblArtista1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jblArtistaFavorito1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jblArtista2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jblNombreArtista1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAvanzarArtista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jblNombreArtista2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jblNombreArtista3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRetrocederArtista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        btnRetrocederAlbum.setBackground(new java.awt.Color(8, 148, 249));
        btnRetrocederAlbum.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnRetrocederAlbum.setForeground(new java.awt.Color(0, 0, 0));
        btnRetrocederAlbum.setText("<");
        btnRetrocederAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocederAlbumActionPerformed(evt);
            }
        });

        btnAvanzarAlbum.setBackground(new java.awt.Color(8, 148, 249));
        btnAvanzarAlbum.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnAvanzarAlbum.setForeground(new java.awt.Color(0, 0, 0));
        btnAvanzarAlbum.setText(">");
        btnAvanzarAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvanzarAlbumActionPerformed(evt);
            }
        });

        jblAlbum1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jblAlbum1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblAlbum1MouseClicked(evt);
            }
        });

        jblAlbum2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jblAlbum2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblAlbum2MouseClicked(evt);
            }
        });

        jblAlbum3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblAlbum3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jblAlbum3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblAlbum3MouseClicked(evt);
            }
        });

        jblNombreAlbum1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblNombreAlbum1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jblNombreAlbum2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblNombreAlbum2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jblNombreAlbum3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jblAlbumFavorito1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jblAlbumFavorito2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jblAlbumFavorito3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRetrocederAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jblAlbum1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jblAlbumFavorito1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jblNombreAlbum1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jblAlbum2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblNombreAlbum2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jblAlbumFavorito2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jblAlbum3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblNombreAlbum3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jblAlbumFavorito3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(btnAvanzarAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jblAlbum1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jblAlbum2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jblAlbum3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jblAlbumFavorito3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jblAlbumFavorito1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jblNombreAlbum1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAvanzarAlbum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRetrocederAlbum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jblNombreAlbum2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jblNombreAlbum3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jblAlbumFavorito2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        btnRetrocederCancion.setBackground(new java.awt.Color(8, 148, 249));
        btnRetrocederCancion.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnRetrocederCancion.setForeground(new java.awt.Color(0, 0, 0));
        btnRetrocederCancion.setText("<");
        btnRetrocederCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocederCancionActionPerformed(evt);
            }
        });

        btnAvanzarCancion.setBackground(new java.awt.Color(8, 148, 249));
        btnAvanzarCancion.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnAvanzarCancion.setForeground(new java.awt.Color(0, 0, 0));
        btnAvanzarCancion.setText(">");
        btnAvanzarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvanzarCancionActionPerformed(evt);
            }
        });

        jblCancion1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jblCancion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblCancion1MouseClicked(evt);
            }
        });

        jblCancion2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jblCancion2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblCancion2MouseClicked(evt);
            }
        });

        jblCancion3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jblCancion3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblCancion3MouseClicked(evt);
            }
        });

        jblNombreCancion1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jblNombreCancion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblNombreCancion1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jblNombreCancion2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jblNombreCancion2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblNombreCancion2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jblNombreCancion3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jblNombreCancion3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblNombreCancion3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jblCancionFavorito1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jblCancionFavorito2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jblCancionFavorito3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRetrocederCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jblNombreCancion1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblCancion1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jblCancionFavorito1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jblCancion2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jblCancionFavorito2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jblNombreCancion2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jblNombreCancion3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnAvanzarCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jblCancion3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jblCancionFavorito3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jblCancionFavorito3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jblCancion2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jblCancion1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jblCancion3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jblCancionFavorito2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jblNombreCancion3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jblNombreCancion1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jblNombreCancion2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnRetrocederCancion)
                                        .addComponent(btnAvanzarCancion))))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jblCancionFavorito1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jblAlbumes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblAlbumes.setForeground(new java.awt.Color(0, 0, 0));
        jblAlbumes.setText("Albumes");

        jblCanciones.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblCanciones.setForeground(new java.awt.Color(0, 0, 0));
        jblCanciones.setText("Canciones");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jblCanciones)
                    .addComponent(jblAlbumes)
                    .addComponent(jblArtistas)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jblArtistas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jblAlbumes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jblCanciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(121, 121, 121)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(123, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(634, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscadorActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnBuscadorActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        // TODO add your handling code here:
        
        perfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void jblArtista1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblArtista1MouseClicked
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(this, "aqui va a haber algo");
    }//GEN-LAST:event_jblArtista1MouseClicked

    private void btnAvanzarArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvanzarArtistaActionPerformed
        // TODO add your handling code here:
        try{
            
            btnRetrocederArtista.setEnabled(true);
            indiceArtistaA = indiceArtistaA + 3;
            if(artistas.get(indiceArtistaA) != null){ 

                jblNombreArtista1.setText(artistas.get(indiceArtistaA).getNombreArtista());
                setImagenLabel(jblArtista1, artistas.get(indiceArtistaA).getImagen());
            
                try{
                    indiceArtistaB = indiceArtistaA + 3;
                    if(artistas.get(indiceArtistaB) != null){ 

                        jblNombreArtista1.setText(artistas.get(indiceArtistaB).getNombreArtista());
                        setImagenLabel(jblArtista1, artistas.get(indiceArtistaB).getImagen());
                        
                        try{
                            indiceArtistaB = indiceArtistaA + 3;
                            if(artistas.get(indiceArtistaC) != null){ 

                                jblNombreArtista1.setText(artistas.get(indiceArtistaC).getNombreArtista());
                                setImagenLabel(jblArtista1, artistas.get(indiceArtistaC).getImagen());
                            }
                        }
                        
                        catch(Exception e){
                            btnRetrocederArtista.setEnabled(false);
                            System.out.println(e.getMessage());
                            JOptionPane.showMessageDialog(this, "No hay mas artistas", "Fin de la lista", JOptionPane.ERROR_MESSAGE);
                            indiceArtistaC = indiceArtistaC - 3;
                            jblNombreArtista3.setText(artistas.get(indiceArtistaC).getNombreArtista());
                            setImagenLabel(jblArtista3, artistas.get(indiceArtistaC).getImagen());
                        }
                    
                    }
            }
            
                catch(Exception e){
                    btnRetrocederArtista.setEnabled(false);
                    System.out.println(e.getMessage());
                    JOptionPane.showMessageDialog(this, "No hay mas artistas", "Fin de la lista", JOptionPane.ERROR_MESSAGE);
                    indiceArtistaB = indiceArtistaB - 3;
                    jblNombreArtista2.setText(artistas.get(indiceArtistaB).getNombreArtista());
                    setImagenLabel(jblArtista2, artistas.get(indiceArtistaB).getImagen());
            }
            
            
            }

        }
        
        catch(Exception e){
            System.out.println(e.getMessage());
            btnRetrocederArtista.setEnabled(false);
            JOptionPane.showMessageDialog(this, "No hay mas artistas", "Fin de la lista", JOptionPane.ERROR_MESSAGE);
            indiceArtistaA = indiceArtistaA - 3;
            jblNombreArtista1.setText(artistas.get(indiceArtistaA).getNombreArtista());
            setImagenLabel(jblArtista1, artistas.get(indiceArtistaA).getImagen());

        }
        
        
    }//GEN-LAST:event_btnAvanzarArtistaActionPerformed

    private void btnAvanzarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvanzarCancionActionPerformed
        // TODO add your handling code here:
        
        try{
            
            btnRetrocederCancion.setEnabled(true);
            indiceCancionA = indiceCancionA + 3;
            if(canciones.get(indiceCancionA) != null){ 

                jblNombreCancion1.setText(canciones.get(indiceCancionA).getNombreCancion());
                setImagenLabel(jblCancion1, negocio.obtenerImagenPorIdCancion(canciones.get(indiceCancionA).getIdCancion()));
            
                try{
                    System.out.println("indice cacnion a" + indiceCancionA);
                    indiceCancionB = indiceCancionB + 3;
                    if(canciones.get(indiceCancionB) != null){ 

                        jblNombreCancion2.setText(canciones.get(indiceCancionB).getNombreCancion());
                        setImagenLabel(jblCancion2, negocio.obtenerImagenPorIdCancion(canciones.get(indiceCancionB).getIdCancion()));
                        
                        try{
                            indiceCancionC = indiceCancionC + 3;
                            if(canciones.get(indiceCancionC) != null){ 

                                jblNombreCancion3.setText(canciones.get(indiceCancionC).getNombreCancion());
                                setImagenLabel(jblCancion3, negocio.obtenerImagenPorIdCancion(canciones.get(indiceCancionC).getIdCancion()));
                            }
                        }
                        
                        catch(Exception e){
                            btnAvanzarCancion.setEnabled(false);
                            System.out.println(e.getMessage());
                            JOptionPane.showMessageDialog(this, "No hay mas canciones", "Fin de la lista", JOptionPane.ERROR_MESSAGE);
                            indiceCancionC = indiceCancionC - 3;
                            jblNombreCancion3.setText(canciones.get(indiceCancionC).getNombreCancion());
                            setImagenLabel(jblCancion3, negocio.obtenerImagenPorIdCancion(canciones.get(indiceCancionC).getIdCancion()));
                        }
                    
                    }
            }
            
                catch(Exception e){
                    btnAvanzarCancion.setEnabled(false);
                    System.out.println(e.getMessage());
                    JOptionPane.showMessageDialog(this, "No hay mas Canciones", "Fin de la lista", JOptionPane.ERROR_MESSAGE);
                    indiceCancionB = indiceCancionB - 3;
                    jblNombreCancion2.setText(canciones.get(indiceCancionB).getNombreCancion());
                    setImagenLabel(jblCancion2, negocio.obtenerImagenPorIdCancion(canciones.get(indiceCancionB).getIdCancion()));
            }
            
            
            }

        }
        
        catch(Exception e){
            btnAvanzarCancion.setEnabled(false);
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this, "No hay mas canciones", "Fin de la lista", JOptionPane.ERROR_MESSAGE);
            indiceCancionA = indiceCancionA - 3;
            jblNombreCancion1.setText(canciones.get(indiceCancionA).getNombreCancion());
            setImagenLabel(jblCancion1, negocio.obtenerImagenPorIdCancion(canciones.get(indiceCancionA).getIdCancion()));

        }        
    }//GEN-LAST:event_btnAvanzarCancionActionPerformed

    private void btnAvanzarAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvanzarAlbumActionPerformed
        // TODO add your handling code here:
       try{
            
            btnRetrocederAlbum.setEnabled(true);
            indiceAlbumA = indiceAlbumA + 3;
            if(albumes.get(indiceAlbumA) != null){ 

                jblNombreAlbum1.setText(albumes.get(indiceAlbumA).getNombre());
                setImagenLabel(jblAlbum1, albumes.get(indiceAlbumA).getImagen());
            
                try{
                    System.out.println("indice album a" + indiceAlbumA);
                    indiceAlbumB = indiceAlbumB + 3;
                    if(albumes.get(indiceAlbumB) != null){ 

                        jblNombreAlbum2.setText(albumes.get(indiceAlbumB).getNombre());
                        setImagenLabel(jblAlbum2, albumes.get(indiceAlbumB).getImagen());
                        
                        try{
                            indiceAlbumC = indiceAlbumC + 3;
                            if(albumes.get(indiceAlbumC) != null){ 

                                jblNombreAlbum3.setText(albumes.get(indiceAlbumC).getNombre());
                                setImagenLabel(jblAlbum3, albumes.get(indiceAlbumC).getImagen());
                            }
                        }
                        
                        catch(Exception e){
                            btnAvanzarAlbum.setEnabled(false);
                            System.out.println(e.getMessage());
                            JOptionPane.showMessageDialog(this, "No hay mas albumes", "Fin de la lista", JOptionPane.ERROR_MESSAGE);
                            indiceAlbumC = indiceAlbumC - 3;
                            jblNombreAlbum3.setText(albumes.get(indiceAlbumC).getNombre());
                            setImagenLabel(jblAlbum3, albumes.get(indiceAlbumC).getImagen());
                        }
                    
                    }
            }
            
                catch(Exception e){
                    btnAvanzarAlbum.setEnabled(false);
                    System.out.println(e.getMessage());
                    JOptionPane.showMessageDialog(this, "No hay mas albumes", "Fin de la lista", JOptionPane.ERROR_MESSAGE);
                    indiceAlbumB = indiceAlbumB - 3;
                    jblNombreAlbum2.setText(albumes.get(indiceAlbumB).getNombre());
                    setImagenLabel(jblAlbum2, albumes.get(indiceAlbumB).getImagen());
            }
            
            
            }

        }
        
        catch(Exception e){
            btnAvanzarAlbum.setEnabled(false);
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this, "No hay mas albumes", "Fin de la lista", JOptionPane.ERROR_MESSAGE);
            indiceAlbumA = indiceAlbumA - 3;
            jblNombreAlbum1.setText(albumes.get(indiceAlbumA).getNombre());
            setImagenLabel(jblAlbum1, albumes.get(indiceAlbumA).getImagen());

        }        
     
        
    }//GEN-LAST:event_btnAvanzarAlbumActionPerformed

    private void btnRetrocederCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrocederCancionActionPerformed
        // TODO add your handling code here:
        try{
            
             btnAvanzarCancion.setEnabled(true);
            indiceCancionA = indiceCancionA - 3;
            if(canciones.get(indiceCancionA) != null){ 

                jblNombreCancion1.setText(canciones.get(indiceCancionA).getNombreCancion());
                setImagenLabel(jblCancion1, negocio.obtenerImagenPorIdCancion(canciones.get(indiceCancionA).getIdCancion()));
            
                try{
                    System.out.println("indice cacnion a" + indiceCancionA);
                    indiceCancionB = indiceCancionB - 3;
                    if(canciones.get(indiceCancionB) != null){ 

                        jblNombreCancion2.setText(canciones.get(indiceCancionB).getNombreCancion());
                        setImagenLabel(jblCancion2, negocio.obtenerImagenPorIdCancion(canciones.get(indiceCancionB).getIdCancion()));
                        
                        try{
                            indiceCancionC = indiceCancionC - 3;
                            if(canciones.get(indiceCancionC) != null){ 

                                jblNombreCancion3.setText(canciones.get(indiceCancionC).getNombreCancion());
                                setImagenLabel(jblCancion3, negocio.obtenerImagenPorIdCancion(canciones.get(indiceCancionC).getIdCancion()));
                            }
                        }
                        
                        catch(Exception e){
                            btnRetrocederCancion.setEnabled(false);
                            System.out.println(e.getMessage());
                            JOptionPane.showMessageDialog(this, "No hay mas canciones", "Inicio de la lista", JOptionPane.ERROR_MESSAGE);
                            indiceCancionC = indiceCancionC + 3;
                            jblNombreCancion3.setText(canciones.get(indiceCancionC).getNombreCancion());
                            setImagenLabel(jblCancion3, negocio.obtenerImagenPorIdCancion(canciones.get(indiceCancionC).getIdCancion()));
                        }
                    
                    }
            }
            
                catch(Exception e){
                    btnRetrocederCancion.setEnabled(false);
                    System.out.println(e.getMessage());
                    JOptionPane.showMessageDialog(this, "No hay mas Canciones", "Inicio de la lista", JOptionPane.ERROR_MESSAGE);
                    indiceCancionB = indiceCancionB + 3;
                    jblNombreCancion2.setText(canciones.get(indiceCancionB).getNombreCancion());
                    setImagenLabel(jblCancion2, negocio.obtenerImagenPorIdCancion(canciones.get(indiceCancionB).getIdCancion()));
            }
            
            
            }

        }
        
        catch(Exception e){
            btnRetrocederCancion.setEnabled(false);
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this, "No hay mas canciones", "Inicio de la lista", JOptionPane.ERROR_MESSAGE);
            indiceCancionA = indiceCancionA + 3;
            jblNombreCancion1.setText(canciones.get(indiceCancionA).getNombreCancion());
            setImagenLabel(jblCancion1, negocio.obtenerImagenPorIdCancion(canciones.get(indiceCancionA).getIdCancion()));

        }        
    
        
    }//GEN-LAST:event_btnRetrocederCancionActionPerformed

    private void btnRetrocederAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrocederAlbumActionPerformed
        // TODO add your handling code here:
        try{
            
            btnAvanzarAlbum.setEnabled(true);
            indiceAlbumA = indiceAlbumA - 3;
            if(albumes.get(indiceAlbumA) != null){ 

                jblNombreAlbum1.setText(albumes.get(indiceAlbumA).getNombre());
                setImagenLabel(jblAlbum1, albumes.get(indiceAlbumA).getImagen());
            
                try{
                    System.out.println("indice album a" + indiceCancionA);
                    indiceAlbumB = indiceAlbumB - 3;
                    if(albumes.get(indiceAlbumB) != null){ 

                        jblNombreAlbum2.setText(albumes.get(indiceAlbumB).getNombre());
                        setImagenLabel(jblAlbum2, albumes.get(indiceAlbumB).getImagen());
                        
                        try{
                            indiceAlbumC = indiceAlbumC - 3;
                            if(albumes.get(indiceAlbumC) != null){ 

                                jblNombreAlbum3.setText(albumes.get(indiceAlbumC).getNombre());
                                setImagenLabel(jblAlbum3, albumes.get(indiceAlbumC).getImagen());
                            }
                        }
                        
                        catch(Exception e){
                            btnRetrocederAlbum.setEnabled(false);
                            System.out.println(e.getMessage());
                            JOptionPane.showMessageDialog(this, "No hay mas albumes", "Inicio de la lista", JOptionPane.ERROR_MESSAGE);
                            indiceAlbumC = indiceAlbumC + 3;
                            jblNombreAlbum3.setText(albumes.get(indiceAlbumC).getNombre());
                            setImagenLabel(jblAlbum3, albumes.get(indiceAlbumC).getImagen());
                        }
                    
                    }
            }
            
                catch(Exception e){
                    btnRetrocederAlbum.setEnabled(false);
                    System.out.println(e.getMessage());
                    JOptionPane.showMessageDialog(this, "No hay mas albumes", "Inicio de la lista", JOptionPane.ERROR_MESSAGE);
                    indiceAlbumB = indiceAlbumB + 3;
                    jblNombreAlbum2.setText(albumes.get(indiceAlbumB).getNombre());
                    setImagenLabel(jblAlbum2, albumes.get(indiceAlbumB).getImagen());
            }
            
            
            }

        }
        
        catch(Exception e){
            btnRetrocederAlbum.setEnabled(false);
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this, "No hay mas albumes", "Inicio de la lista", JOptionPane.ERROR_MESSAGE);
            indiceAlbumA = indiceAlbumA + 3;
            jblNombreAlbum1.setText(albumes.get(indiceAlbumA).getNombre());
            setImagenLabel(jblAlbum1, albumes.get(indiceAlbumA).getImagen());

        }

    }//GEN-LAST:event_btnRetrocederAlbumActionPerformed

    private void btnRetrocederArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrocederArtistaActionPerformed
        // TODO add your handling code here:
        try{
            
            btnAvanzarArtista.setEnabled(true);
            indiceArtistaA = indiceArtistaA - 3;
            if(artistas.get(indiceArtistaA) != null){ 

                jblNombreArtista1.setText(artistas.get(indiceArtistaA).getNombreArtista());
                setImagenLabel(jblArtista1, artistas.get(indiceArtistaA).getImagen());
            
                try{
                    indiceArtistaB = indiceArtistaB - 3;
                    if(artistas.get(indiceArtistaB) != null){ 

                        jblNombreArtista2.setText(artistas.get(indiceArtistaB).getNombreArtista());
                        setImagenLabel(jblArtista2, artistas.get(indiceArtistaB).getImagen());
                        
                        try{
                            indiceArtistaC = indiceArtistaC - 3;
                            if(artistas.get(indiceArtistaC) != null){ 

                                jblNombreArtista3.setText(artistas.get(indiceArtistaC).getNombreArtista());
                                setImagenLabel(jblArtista3, artistas.get(indiceArtistaC).getImagen());
                            }
                        }
                        
                        catch(Exception e){
                            btnRetrocederArtista.setEnabled(false);
                            System.out.println(e.getMessage());
                            JOptionPane.showMessageDialog(this, "No hay mas artistas", "Fin de la lista", JOptionPane.ERROR_MESSAGE);
                            indiceArtistaC =- 3;
                            jblNombreArtista3.setText(artistas.get(indiceArtistaC).getNombreArtista());
                            setImagenLabel(jblArtista3, artistas.get(indiceArtistaC).getImagen());
                        }
                    
                    }
            }
            
                catch(Exception e){
                    btnRetrocederArtista.setEnabled(false);
                    System.out.println(e.getMessage());
                    JOptionPane.showMessageDialog(this, "No hay mas artistas", "Fin de la lista", JOptionPane.ERROR_MESSAGE);
                    indiceAlbumB = indiceAlbumB - 3;
                    jblNombreArtista2.setText(artistas.get(indiceArtistaB).getNombreArtista());
                    setImagenLabel(jblArtista2, artistas.get(indiceArtistaB).getImagen());
            }
            
            
            }

        }
        
        catch(Exception e){
            btnRetrocederArtista.setEnabled(false);
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this, "No hay mas artistas", "Fin de la lista", JOptionPane.ERROR_MESSAGE);
            indiceAlbumA = indiceAlbumA - 3;
            jblNombreArtista1.setText(artistas.get(indiceArtistaA).getNombreArtista());
            setImagenLabel(jblArtista1, artistas.get(indiceArtistaA).getImagen());

        }
    }//GEN-LAST:event_btnRetrocederArtistaActionPerformed

    private void jblArtista2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblArtista2MouseClicked
        // TODO add your handling code here:
                JOptionPane.showMessageDialog(this, "aqui va a haber algo");

    }//GEN-LAST:event_jblArtista2MouseClicked

    private void jblArtista3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblArtista3MouseClicked
        // TODO add your handling code here:
                JOptionPane.showMessageDialog(this, "aqui va a haber algo");

    }//GEN-LAST:event_jblArtista3MouseClicked

    private void jblAlbum1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblAlbum1MouseClicked
        // TODO add your handling code here:
                JOptionPane.showMessageDialog(this, "aqui va a haber algo");

    }//GEN-LAST:event_jblAlbum1MouseClicked

    private void jblAlbum2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblAlbum2MouseClicked
        // TODO add your handling code here:
                JOptionPane.showMessageDialog(this, "aqui va a haber algo");

    }//GEN-LAST:event_jblAlbum2MouseClicked

    private void jblAlbum3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblAlbum3MouseClicked
        // TODO add your handling code here:
                JOptionPane.showMessageDialog(this, "aqui va a haber algo");

    }//GEN-LAST:event_jblAlbum3MouseClicked

    private void jblCancion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblCancion1MouseClicked
        // TODO add your handling code here:
                JOptionPane.showMessageDialog(this, "aqui va a haber algo");

    }//GEN-LAST:event_jblCancion1MouseClicked

    private void jblCancion2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblCancion2MouseClicked
        // TODO add your handling code here:
                JOptionPane.showMessageDialog(this, "aqui va a haber algo");

    }//GEN-LAST:event_jblCancion2MouseClicked

    private void jblCancion3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblCancion3MouseClicked
        // TODO add your handling code here:
                JOptionPane.showMessageDialog(this, "aqui va a haber algo");

    }//GEN-LAST:event_jblCancion3MouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvanzarAlbum;
    private javax.swing.JButton btnAvanzarArtista;
    private javax.swing.JButton btnAvanzarCancion;
    private javax.swing.JButton btnBuscador;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnFiltros;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnRetrocederAlbum;
    private javax.swing.JButton btnRetrocederArtista;
    private javax.swing.JButton btnRetrocederCancion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel jblAlbum1;
    private javax.swing.JLabel jblAlbum2;
    private javax.swing.JLabel jblAlbum3;
    private javax.swing.JLabel jblAlbumFavorito1;
    private javax.swing.JLabel jblAlbumFavorito2;
    private javax.swing.JLabel jblAlbumFavorito3;
    private javax.swing.JLabel jblAlbumes;
    private javax.swing.JLabel jblArtista1;
    private javax.swing.JLabel jblArtista2;
    private javax.swing.JLabel jblArtista3;
    private javax.swing.JLabel jblArtistaFavorito1;
    private javax.swing.JLabel jblArtistaFavorito2;
    private javax.swing.JLabel jblArtistaFavorito3;
    private javax.swing.JLabel jblArtistas;
    private javax.swing.JLabel jblBuscar;
    private javax.swing.JLabel jblCancion1;
    private javax.swing.JLabel jblCancion2;
    private javax.swing.JLabel jblCancion3;
    private javax.swing.JLabel jblCancionFavorito1;
    private javax.swing.JLabel jblCancionFavorito2;
    private javax.swing.JLabel jblCancionFavorito3;
    private javax.swing.JLabel jblCanciones;
    private javax.swing.JLabel jblNombreAlbum1;
    private javax.swing.JLabel jblNombreAlbum2;
    private javax.swing.JLabel jblNombreAlbum3;
    private javax.swing.JLabel jblNombreArtista1;
    private javax.swing.JLabel jblNombreArtista2;
    private javax.swing.JLabel jblNombreArtista3;
    private javax.swing.JLabel jblNombreArtista5;
    private javax.swing.JLabel jblNombreCancion1;
    private javax.swing.JLabel jblNombreCancion2;
    private javax.swing.JLabel jblNombreCancion3;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
